### ISSUE TITLE
Wiki Request: List of recommended plugin/addon sources

### ISSUE THREAD

**Issue by ndtreviv** [cubeworx/mcbe-server#12]
Hello! 

I've come here via https://github.com/itzg/docker-minecraft-bedrock-server and was so pleased to see that you've got addons working.
My kids are connecting to the world via the Nintendo Switch (and Bedrock Connect - https://github.com/Pugmatt/BedrockConnect).
I'm really keen to find a source of addons that are known to work. Do you have any links to any directories etc? Could this be something you put in the Wiki on this repo?

Similarly, is it possible to run a LAN game on Docker that multiple Nintendo Switch-es can connect to? The server doesn't show up on the switch when attempting to connect locally. (Perhaps something that could be added to FAQ on the wiki or similar?)

Thanks for all your work on this!

**Comment by claflico** [comment]
Hi Nathan,

Happy new year!

The QA team (my sons) have advanced from playing Bedrock edition on Fire tablets to Java edition on Macs since I first started working on these images so we haven't had the chance to test many addons or mods just yet. They do still play Bedrock edition on their tablets when we're traveling but don't play on the Bedrock server as much as they used to.

Our ultimate vision is that compatible addons, seeds, worlds, etc. would all be added to a database with a rest api that the local cubeworx web interface would connect to and parents/kids would be able to click check boxes for what they wanted installed when a server gets launched.

For now I'll add an Addons.md file to the repo and as people report ones that they've confirmed working/not-working I'll add them to the respective section. Adding it as a .md file would allow others to contribute via PRs too whereas the Wiki would require me to maintain it.

We just got a Nintendo switch with an online subscription and I confirmed that our local servers doesn't show up on it like they does on our tablets/phones. [cbwxannounce](https://github.com/cubeworx/cbwxannounce) is required to have multiple servers running on the same host show up under LAN on their respective clients so I'll see what it takes to get it working with BedrockConnect.

**Comment by ndtreviv** [comment]
Hello and Happy New Year!

That sounds amazing - happy to contribute or help in any way I can. 
Most of the addons I've tried seem to _sort_ of work. I've worked out that The ones that totally work aren't dependent upon the Experiments switches, which I've mentioned in that other issue (#13 )

I've also since learned that LAN games basically just aren't supported by the Switch - another reason not to play it on a Switch! Unfortunately it's our only console, so we're working around things as much as we can.
I want to run worlds with minigames (like sky wars etc) but that are sandboxed to my kids and their friends. I have a mac mini that I'm running everything on, just need to work out how to connect up all the pieces.

Thanks for all your hard work on this! It's very much appreciated!
